[58414] When you click on the "To the Notification Center" button, an outline appears
opf/openproject-octicons pull request #69
Opened 2024-10-21 13:16 UTC by bsatarnejad

When clicking on an octicon, there is an outline around it, it is related to the tabIndex set to it.
We need to remove it from the component.

https://community.openproject.org/projects/openproject/work_packages/58414/activity

2024-10-22 05:54 UTC, HDinger requested changes
Hi @bsatarnejad 

please do not touch the react code, as it is coming directly from Primer and will only cause merge conflicts if we touch it. Further, we are not using the React components at all.. 
Looking however at the react code, I notifced that the tabIndex is optional there with no default set. So if we aim for consistency, we should probably still allow the tabIndex but not set a default. What do you think?

2024-10-22 06:01 UTC, bsatarnejad commented
> Hi @bsatarnejad
> 
> please do not touch the react code, as it is coming directly from Primer and will only cause merge conflicts if we touch it. Further, we are not using the React components at all.. Looking however at the react code, I notifced that the tabIndex is optional there with no default set. So if we aim for consistency, we should probably still allow the tabIndex but not set a default. What do you think?

Hi @HDinger 
I agree with making tabIndex optional in the sake of consistency. 👍

2024-10-24 06:13 UTC, HDinger commented on lib/octicons_angular/src/octicon-component-base.ts
> +    return this.tabIndex != null ? this.tabIndex : null;
Shouldn't this be enough?

```suggestion
    return this.tabIndex;
```

2024-10-24 06:14 UTC, HDinger approved these changes
I just have one minor remark. Otherwise it is looking fine 👍

2024-10-24 08:17 UTC, merged